# Generated by Django 4.1.6 on 2023-03-23 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_enrollment_course_alter_enrollment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='datetime',
            field=models.DateTimeField(default=None),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons', models.ManyToManyField(related_name='lessons', to='api.courses')),
                ('teachers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('related_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_course', to='api.courses')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='api.teacher')),
            ],
        ),
    ]
