# Generated by Django 4.1.6 on 2023-03-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_lessons_unique_together_lessons_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='datetime',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='lessons',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='api.lessons'),
        ),
    ]
