# Generated by Django 4.1.6 on 2023-03-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_lessons_join_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='start_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
